### ISSUE TITLE
[v 6.69]输入框删减文本导致软件奔溃

### ISSUE THREAD

**Issue by kihlh** [qiusunshine/youtoo#3]
复现概率: 每次
软件版本: 6.69    X64
系统版本:Android 12 MIUI
复现方式:

1. 输入框输入 
```
21 屁屁小皇弟发布了一篇小红书笔记，快来看吧！ 😆 WYolFzz8Z71d0d8 😆 http://xhslink.com/a/99yXndR7Qra1，复制本条信息，打开【小红书】App查看精彩内容！
```
2.删减文本到第一个字就会导致软件奔溃

**Comment by qiusunshine** [comment]
试试内测版，内测版地址：https://www.123pan.com/s/fajA-S1qQh.html



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月7日(周六) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiusunshine/youtoo] [v 6.69]输入框删减文本导致软件奔溃 (Issue #3)




 
复现概率: 每次
 软件版本: 6.69    X64
 系统版本:Android 12 MIUI
 复现方式:
  
输入框输入
  21 屁屁小皇弟发布了一篇小红书笔记，快来看吧！ 😆 WYolFzz8Z71d0d8 😆 http://xhslink.com/a/99yXndR7Qra1，复制本条信息，打开【小红书】App查看精彩内容！  
2.删减文本到第一个字就会导致软件奔溃

**Comment by kihlh** [comment]
6.70特殊字符下有问题

#### 没问题: 
```
http://xhslink.com/a/99yXndR7Qra1
```

#### 有问题:
```
ЗX59I4mN4rGP1cd3
```

```
ЗX3
```


- 他这里的3是个特殊字符的3，应该是某个软件生成的口令，占了2个长度，如果出现一次З不会导致奔溃，如果两个及以上会奔溃，应该是字节长度少算或者多算了

**Comment by qiusunshine** [comment]
不管是海阔视界还是嗅觉浏览器，我都测试过了没任何问题，不管是你给的长口令还是那个短的，以下是录屏
https://www.123865.com/s/fajA-WlTEh



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月7日(周六) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiusunshine/youtoo] [v 6.69]输入框删减文本导致软件奔溃 (Issue #3)




 
6.70特殊字符下有问题
 
没问题:
 http://xhslink.com/a/99yXndR7Qra1  
有问题:
 ЗX59I4mN4rGP1cd3  ЗX3   
他这里的3是个特殊字符的3，应该是某个软件生成的口令，占了2个长度，如果出现一次З不会导致奔溃，如果两个及以上会奔溃，应该是字节长度少算或者多算了

**Comment by kihlh** [comment]
那没事了🤔  低复现可能性就不纠结了
